### ISSUE TITLE
[ install ] Building the `.ipkg` file installs `.so` files

### ISSUE THREAD

**Issue by stefan-hoeck** [ECburx/IdrisGL#10] opened 2023-01-17 13:26 UTC
I'm not an expert in `Makefile`s, but if I understand correctly, `make prebuild` (which is run when invoking `idris2 --build idrisGL.ipkg`) installs generated `.so` files to `idris2 --libdir`. This is an issue with pack, as those artifacts have to go to a different location when using pack, otherwise it would not be possible to have different versions of idrisGL (from different pack collections) installed at the same time.

If pack finds a directory called `lib` in the same directory as the `.ipkg` it works on, it will automatically copy its content to the correct location. `make prebuild` should therefore create such a directory and copy the `.so` files there without installing them anywhere else.

**Comment by ECburx** [comment] 2023-01-18 08:01
Hi,
Yes, what you said about the current `Makefile` is correct. Apparently, I know less about how exactly Pack works as a package manager than you do. To address the issue you mentioned, does it mean `make prebuild` should

1. generate all `.so` files
2. put them in a folder, say `lib`. `lib` is in the same directory as `idrisGL.ipkg` located in
3. Pack will take care of the rest: automatically copying `lib` and it's content to the correct location

**Comment by stefan-hoeck** [comment] 2023-01-18 09:29
Yes, that's correct, and the folder's name must be `lib` (that's the name pack is expecting).

**Comment by ECburx** [comment] 2023-01-19 12:59
I think the issue is fixed now, verified using `nightly-230118.toml`. If any problem remains, we could reopen this issue.

**Closed as completed by ECburx** 2023-01-19 12:59 UTC
